//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Complex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int GoodId { get; set; }
        public int RecipientTitle { get; set; }
        public string SupplientName { get; set; }
        public int RecipientName { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Recipient Recipient { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
