//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Complex
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLocation
    {
        public int Id { get; set; }
        public int GoodId { get; set; }
        public int WarehouseId { get; set; }
        public int NumberShelf { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
